name: github-actions-SQAdemo
on:
  push:
  pull_request:
jobs:
  vv-check-SQA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Show working directory
        run: pwd && find . -name "verify.py"
      - name: Run Verification
        run: python scripts/verify.py